version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"

  postgres:
    ports:
      - "5432:5432"
